# Official tutorial 
# MkDocs: https://www.mkdocs.org/user-guide/configuration/
# MkDocs-Material: https://squidfunk.github.io/mkdocs-material/

site_name: 碧蓝档案 民间网站
site_description: 手机游戏《蔚蓝档案》的民间网页项目。
site_url: https://bluearchive-website.pages.dev/
# site_url: http://www.example.com/

# GitHub Repo link
repo_url: https://github.com/Blue-Archive-Website/Website/
repo_name: 在 GitHub 上查看
# 如果存储库 URL 指向有效的 GitHub、GitLab 或 Bitbucket 存储库， 则 MkDocs 会提供一个名为 `edit_uri` 的设置，该设置将解析为托管文档的子文件夹。
edit_uri: edit/main/docs/

# 自定义导航栏
nav:
  - 首页: index.md
  - 角色列表:
    - 'Characters/index.md'
    - 才羽绿: 
      - 'Characters/Saiba-Midori/index.md'
      - 文章:
        - 'Characters/Saiba-Midori/Article/2025-05-17_22-33_Midori.md'

theme:
  name: material

  # 扩展 MkDocs-Material 主题
  custom_dir: overrides

  # 设置站点徽标与标签页图标，支持 PNG 与 SVG
  logo: img/favicon.png
  favicon: img/favicon.ico

  language: zh # 中文，解决中文搜索问题
  features:
    - navigation.expand
    - tabs

    # 自定义页脚（显示上一页和下一页的链接）
    # - navigation.footer

    # 将菜单呈现在位于上述视口标题下方的菜单层中。
    - navigation.tabs

    # 如果 repo_url 和 edit_uri 配置正确，则可以添加此按钮
    # 查看页面源代码
    - content.action.view
    # 编辑页面
    - content.action.edit

    # 启用部分后，对于超过 1220 像素的视口，顶级部分将在侧边栏中呈现为组，但在移动设备上保持原样。
    - navigation.sections

    # 启用区域索引页面后，文档可以直接附加到区域，这对于提供概述页面特别有用。
    - navigation.indexes

    # 当用户向下滚动后再次开始向上滚动时，可以显示返回顶部按钮。它呈现在标题的正下方。
    - navigation.top

  # 提供切换 日间 / 夜间 模式的选项
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        # name: Switch to light mode
        name: 切换到明亮模式

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        # name: Switch to dark mode
        name: 切换到暗黑模式

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        # name: Switch to system preference
        name: 切换到系统偏好

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Blue-Archive-Website/

  # 配置站点分析
  analytics:
    provider: google
    property: G-58M9KRDV23

markdown_extensions: 
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/

  # 文档内嵌图标支持
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # - pymdownx.tabbed  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - nl2br # newline-to-break 
  - toc:
      permalink: '#' # heading anchor 
      slugify: !!python/object/apply:pymdownx.slugs.slugify # 解决中文标题解析问题
        kwds:
          case: lower
          max_length: 64
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
      # emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  # - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

  # Tab 选项卡支持
  # - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  # 流程图支持
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # 网格卡片
  # - attr_list
  - md_in_html

plugins:
  - search

  # 新版貌似支持相对链接了？
  # [日志] INFO - DeprecationWarning: warning_filter doesn't do anything since MkDocs 1.2 and will be removed soon. All messages on the `mkdocs` logger get counted automatically.
  # - roamlinks 

  # 灯箱，提供沉浸式的图片显示效果
  - glightbox

  # 在页面底部显示 Git 编辑日期信息(需要进行一些配置，具体参见 https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/ 文档。)
  # 如果站点托管在 Cloudflare Pages，则参阅 https://pumpkinjui.pages.dev/blog/2025/03/22/pages_fetch_depth.html 。
  - git-revision-date-localized:
      enable_creation_date: true
      # 默认值为 `false`。当 Git 不可用时，启用此选项将回退到执行 `mkdocs build` 命令时的时间戳作为修订日期。这意味着修订日期可能不准确，但如果您希望项目在没有 Git 访问权限的环境中也能成功构建，这种处理方式是可接受的。
      fallback_to_build_date: true

      type: iso_datetime
      # 设置时区
      timezone: Asia/Shanghai

  - social: # 社交卡片 插件
      cards_layout_options:
        # 中文字体，解决默认字体无 CJK 字符的问题
        font_family: Noto Sans SC

  # - autolinks 

  # MkDocs 排除插件，让 `docs` 文件夹中的指定文件不进入构建的站点目录中。
  - exclude:
      glob:
        - "*.tmp"
        - "*.pdf"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'

copyright: Copyright &copy; 2025 KFACBT. All rights reserved.
